[2024-10-23 12:30:44,029: INFO: main: Welcome to our custom log]
[2024-10-24 11:38:45,331: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-24 11:38:45,338: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-24 11:38:45,341: INFO: common: created directory at: artifacts]
[2024-10-24 11:38:45,343: INFO: common: created directory at: artifacts/data_ingestion]
[2024-10-24 11:38:45,344: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-24 11:38:54,661: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-24 13:09:41,966: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-24 13:09:41,971: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-24 13:09:41,974: INFO: common: created directory at: artifacts]
[2024-10-24 13:09:41,976: INFO: common: created directory at: artifacts/data_ingestion]
[2024-10-24 13:09:41,979: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-24 13:09:51,796: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-24 13:15:53,443: ERROR: main: name 'STAGE_NAME' is not defined]
Traceback (most recent call last):
  File "C:\Users\islam\Downloads\kidney-Disease-classification-Deep-learning-project\main.py", line 17, in <module>
    logger.info(f">>>>>> stage {STAGE_NAME} started <<<<<<")
NameError: name 'STAGE_NAME' is not defined
[2024-10-24 13:18:52,764: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-10-24 13:18:52,767: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-24 13:18:52,769: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-24 13:18:52,770: INFO: common: created directory at: artifacts]
[2024-10-24 13:18:52,771: INFO: common: created directory at: artifacts/data_ingestion]
[2024-10-24 13:18:52,772: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-24 13:19:02,384: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-24 13:19:04,098: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-10-25 11:07:56,193: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-25 11:07:56,222: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-25 11:07:56,248: INFO: common: created directory at: artifacts]
[2024-10-25 11:07:56,251: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-10-25 11:08:11,816: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-10-25 11:33:04,668: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-25 11:33:04,676: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-25 11:33:04,676: INFO: common: created directory at: artifacts]
[2024-10-25 11:33:04,680: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-10-25 11:33:05,472: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-10-25 11:45:00,181: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-10-25 11:45:00,181: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-25 11:45:00,197: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-25 11:45:00,197: INFO: common: created directory at: artifacts]
[2024-10-25 11:45:00,197: ERROR: main: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config']
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    obj.main()
  File "C:\Users/islam/Downloads/kidney-Disease-classification-Deep-learning-project/src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 14, in main
    data_ingestion_config = config.get_data_ingestion_config()
AttributeError: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config'
[2024-10-25 12:14:35,792: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-10-25 12:14:35,809: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-25 12:14:35,809: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-25 12:14:35,809: INFO: common: created directory at: artifacts]
[2024-10-25 12:14:35,809: INFO: common: created directory at: artifacts/data_ingestion]
[2024-10-25 12:14:35,809: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-25 12:14:48,568: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-25 12:14:53,298: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-10-25 12:14:53,298: INFO: main: *******************]
[2024-10-25 12:14:53,298: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-10-25 12:14:53,298: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-25 12:14:53,298: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-25 12:14:53,313: INFO: common: created directory at: artifacts]
[2024-10-25 12:14:53,313: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-10-25 12:14:55,703: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-10-25 12:14:57,020: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-10-25 12:49:44,422: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-25 12:49:44,434: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-25 12:49:44,436: INFO: common: created directory at: artifacts]
[2024-10-25 12:49:44,438: INFO: common: created directory at: artifacts\training]
[2024-10-25 12:58:04,197: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-25 12:58:04,207: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-25 12:58:04,209: INFO: common: created directory at: artifacts]
[2024-10-25 12:58:04,211: INFO: common: created directory at: artifacts\training]
[2024-10-25 12:59:03,139: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-25 12:59:03,139: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-25 12:59:03,139: INFO: common: created directory at: artifacts]
[2024-10-25 12:59:03,155: INFO: common: created directory at: artifacts\training]
[2024-10-25 13:01:40,526: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-25 13:01:40,541: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-25 13:01:40,543: INFO: common: created directory at: artifacts]
[2024-10-25 13:01:40,544: INFO: common: created directory at: artifacts\training]
[2024-10-25 14:39:15,477: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-10-25 14:39:15,493: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-25 14:39:15,494: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-25 14:39:15,494: INFO: common: created directory at: artifacts]
[2024-10-25 14:39:15,494: INFO: common: created directory at: artifacts/data_ingestion]
[2024-10-25 14:39:15,494: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-25 14:39:25,147: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-25 14:39:26,689: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-10-25 14:39:26,704: INFO: main: *******************]
[2024-10-25 14:39:26,704: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-10-25 14:39:26,704: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-25 14:39:26,704: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-25 14:39:26,704: INFO: common: created directory at: artifacts]
[2024-10-25 14:39:26,704: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-10-25 14:39:38,157: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-10-25 14:39:38,858: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-10-25 14:39:38,858: INFO: main: *******************]
[2024-10-25 14:39:38,858: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-10-25 14:39:38,870: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-25 14:39:38,870: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-25 14:39:38,870: INFO: common: created directory at: artifacts]
[2024-10-25 14:39:38,870: INFO: common: created directory at: artifacts\training]
[2024-10-25 14:42:02,440: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-10-28 15:28:54,845: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-28 15:28:55,013: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-28 15:28:55,026: INFO: common: created directory at: artifacts]
[2024-10-28 15:28:55,028: INFO: common: created directory at: artifacts/data_ingestion]
[2024-10-28 15:28:55,029: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-28 15:29:05,214: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-28 15:50:47,419: INFO: common: yaml file: C:\Users\islam\Downloads\kidney-Disease-classification-Deep-learning-project\config\config.yaml loaded successfully]
[2024-10-28 15:50:47,465: INFO: common: yaml file: C:\Users\islam\Downloads\kidney-Disease-classification-Deep-learning-project\params.yaml loaded successfully]
[2024-10-28 15:50:47,502: INFO: common: created directory at: artifacts]
[2024-10-28 15:50:47,504: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-10-28 15:50:52,137: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-10-28 15:53:44,212: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-28 15:53:44,212: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-28 15:53:44,224: INFO: common: created directory at: artifacts]
[2024-10-28 15:55:21,309: INFO: common: yaml file: C:\Users\islam\Downloads\kidney-Disease-classification-Deep-learning-project\config\config.yaml loaded successfully]
[2024-10-28 15:55:21,309: INFO: common: yaml file: C:\Users\islam\Downloads\kidney-Disease-classification-Deep-learning-project\params.yaml loaded successfully]
[2024-10-28 15:55:21,309: INFO: common: created directory at: artifacts]
[2024-10-28 15:55:21,320: INFO: common: created directory at: artifacts\training]
[2024-10-28 15:56:03,143: INFO: common: yaml file: C:\Users\islam\Downloads\kidney-Disease-classification-Deep-learning-project\config\config.yaml loaded successfully]
[2024-10-28 15:56:03,143: INFO: common: yaml file: C:\Users\islam\Downloads\kidney-Disease-classification-Deep-learning-project\params.yaml loaded successfully]
[2024-10-28 15:56:03,150: INFO: common: created directory at: artifacts]
[2024-10-28 15:56:03,152: INFO: common: created directory at: artifacts\training]
[2024-10-28 15:56:09,451: WARNING: ag_logging: AutoGraph could not transform <function Model.make_train_function.<locals>.train_function at 0x000001E735887C10> and will run it as-is.
Cause: Unable to locate the source code of <function Model.make_train_function.<locals>.train_function at 0x000001E735887C10>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert]
[2024-10-28 15:57:22,827: WARNING: ag_logging: AutoGraph could not transform <function Model.make_test_function.<locals>.test_function at 0x000001E730CCAF70> and will run it as-is.
Cause: Unable to locate the source code of <function Model.make_test_function.<locals>.test_function at 0x000001E730CCAF70>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert]
[2024-10-28 16:23:08,674: INFO: common: yaml file: C:\Users\islam\Downloads\kidney-Disease-classification-Deep-learning-project\config\config.yaml loaded successfully]
[2024-10-28 16:23:08,688: INFO: common: yaml file: C:\Users\islam\Downloads\kidney-Disease-classification-Deep-learning-project\params.yaml loaded successfully]
[2024-10-28 16:23:08,692: INFO: common: created directory at: artifacts]
[2024-10-28 16:23:08,695: INFO: common: created directory at: artifacts\training]
[2024-10-28 16:23:10,775: WARNING: ag_logging: AutoGraph could not transform <function Model.make_train_function.<locals>.train_function at 0x000001E730DC4C10> and will run it as-is.
Cause: Unable to locate the source code of <function Model.make_train_function.<locals>.train_function at 0x000001E730DC4C10>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert]
[2024-10-28 16:24:09,779: WARNING: ag_logging: AutoGraph could not transform <function Model.make_test_function.<locals>.test_function at 0x000001E730E809D0> and will run it as-is.
Cause: Unable to locate the source code of <function Model.make_test_function.<locals>.test_function at 0x000001E730E809D0>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert]
[2024-10-29 13:14:41,659: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 13:14:41,688: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 13:14:41,691: INFO: common: created directory at: artifacts]
[2024-10-29 13:14:41,691: INFO: common: created directory at: artifacts\training]
[2024-10-29 13:50:48,273: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 13:50:48,284: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 13:50:48,287: INFO: common: created directory at: artifacts]
[2024-10-29 13:52:18,031: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 13:52:18,046: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 13:52:18,048: INFO: common: created directory at: artifacts]
[2024-10-29 13:53:39,838: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 13:53:39,838: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 13:53:39,850: INFO: common: created directory at: artifacts]
[2024-10-29 13:54:00,719: INFO: common: json file saved at: scores.json]
[2024-10-29 13:54:07,610: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-10-29 13:54:09,697: INFO: builder_impl: Assets written to: C:\Users\islam\AppData\Local\Temp\tmpa8iuhjs_\model\data\model\assets]
[2024-10-29 14:07:44,721: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 14:07:44,724: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 14:07:44,767: INFO: common: created directory at: artifacts]
[2024-10-29 14:08:16,135: INFO: common: json file saved at: scores.json]
[2024-10-29 14:08:19,619: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-10-29 14:08:21,249: INFO: builder_impl: Assets written to: C:\Users\islam\AppData\Local\Temp\tmpynzfb6zd\model\data\model\assets]
[2024-10-29 14:12:59,712: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 14:12:59,723: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 14:12:59,725: INFO: common: created directory at: artifacts]
[2024-10-29 14:13:27,912: INFO: common: json file saved at: scores.json]
[2024-10-29 14:13:31,406: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-10-29 14:13:33,259: INFO: builder_impl: Assets written to: C:\Users\islam\AppData\Local\Temp\tmpurzwlaq5\model\data\model\assets]
[2024-10-29 14:39:44,203: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-10-29 14:39:44,203: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 14:39:44,219: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 14:39:44,219: INFO: common: created directory at: artifacts]
[2024-10-29 14:39:44,219: INFO: common: created directory at: artifacts/data_ingestion]
[2024-10-29 14:39:44,219: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-29 14:39:54,481: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-29 14:39:56,497: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-10-29 14:39:56,497: INFO: main: *******************]
[2024-10-29 14:39:56,499: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-10-29 14:39:56,502: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 14:39:56,508: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 14:39:56,508: INFO: common: created directory at: artifacts]
[2024-10-29 14:39:56,508: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-10-29 14:39:57,446: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-10-29 14:39:58,503: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-10-29 14:39:58,503: INFO: main: *******************]
[2024-10-29 14:39:58,503: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-10-29 14:39:58,503: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 14:39:58,518: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 14:39:58,518: INFO: common: created directory at: artifacts]
[2024-10-29 14:39:58,518: INFO: common: created directory at: artifacts\training]
[2024-10-29 14:41:09,520: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-10-29 14:41:09,520: INFO: main: *******************]
[2024-10-29 14:41:09,521: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-10-29 14:41:09,525: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 14:41:09,526: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 14:41:09,526: INFO: common: created directory at: artifacts]
[2024-10-29 14:41:29,665: INFO: common: json file saved at: scores.json]
[2024-10-29 14:41:29,673: INFO: common: json file saved at: scores.json]
[2024-10-29 14:41:29,673: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-10-29 15:22:28,033: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-10-29 15:22:28,033: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 15:22:28,049: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 15:22:28,049: INFO: common: created directory at: artifacts]
[2024-10-29 15:22:28,049: INFO: common: created directory at: artifacts/data_ingestion]
[2024-10-29 15:22:28,049: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-29 15:22:37,638: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-29 15:22:40,126: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-10-29 15:22:40,126: INFO: main: *******************]
[2024-10-29 15:22:40,134: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-10-29 15:22:40,136: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 15:22:40,136: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 15:22:40,172: INFO: common: created directory at: artifacts]
[2024-10-29 15:22:40,174: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-10-29 15:22:40,862: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-10-29 15:22:41,957: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-10-29 15:22:41,957: INFO: main: *******************]
[2024-10-29 15:22:41,957: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-10-29 15:22:41,957: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 15:22:42,041: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 15:22:42,041: INFO: common: created directory at: artifacts]
[2024-10-29 15:22:42,041: INFO: common: created directory at: artifacts\training]
[2024-10-29 15:24:01,457: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-10-29 15:24:01,457: INFO: main: *******************]
[2024-10-29 15:24:01,457: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-10-29 15:24:01,465: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 15:24:01,467: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 15:24:01,467: INFO: common: created directory at: artifacts]
[2024-10-29 15:24:43,789: INFO: common: json file saved at: scores.json]
[2024-10-29 15:24:43,791: INFO: common: json file saved at: scores.json]
[2024-10-29 15:24:57,162: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-10-29 15:24:58,714: INFO: builder_impl: Assets written to: C:\Users\islam\AppData\Local\Temp\tmpvlnog0mq\model\data\model\assets]
[2024-10-29 15:25:46,607: ERROR: main: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 61, in <module>
    model_evalution.main()
  File "C:\Users/islam/Downloads/kidney-Disease-classification-Deep-learning-project/src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "C:\Users/islam/Downloads/kidney-Disease-classification-Deep-learning-project/src\cnnClassifier\components\model_evaluation_mlflow.py", line 80, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model", registered_model_name="VGG16Model")
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\mlflow\tensorflow\__init__.py", line 217, in log_model
    return Model.log(
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\mlflow\models\model.py", line 789, in log
    registered_model = mlflow.tracking._model_registry.fluent._register_model(
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 103, in _register_model
    raise e
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 92, in _register_model
    create_model_response = client.create_registered_model(name)
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 3109, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\mlflow\tracking\_model_registry\client.py", line 64, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\mlflow\store\model_registry\rest_store.py", line 82, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\mlflow\store\model_registry\base_rest_store.py", line 44, in _call_endpoint
    return call_endpoint(
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 370, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 246, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: ''
[2024-10-29 15:31:57,009: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-10-29 15:31:57,009: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 15:31:57,009: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 15:31:57,009: INFO: common: created directory at: artifacts]
[2024-10-29 15:31:57,009: INFO: common: created directory at: artifacts/data_ingestion]
[2024-10-29 15:31:57,025: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-29 15:32:06,466: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-29 15:32:07,769: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-10-29 15:32:07,769: INFO: main: *******************]
[2024-10-29 15:32:07,769: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-10-29 15:32:07,769: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 15:32:07,769: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 15:32:07,769: INFO: common: created directory at: artifacts]
[2024-10-29 15:32:07,769: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-10-29 15:32:08,394: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-10-29 15:32:09,946: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-10-29 15:32:09,946: INFO: main: *******************]
[2024-10-29 15:32:09,962: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-10-29 15:32:09,962: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 15:32:09,978: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 15:32:09,978: INFO: common: created directory at: artifacts]
[2024-10-29 15:32:09,978: INFO: common: created directory at: artifacts\training]
[2024-10-29 15:33:14,443: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-10-29 15:33:14,443: INFO: main: *******************]
[2024-10-29 15:33:14,443: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-10-29 15:33:14,443: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 15:33:14,443: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 15:33:14,443: INFO: common: created directory at: artifacts]
[2024-10-29 15:33:34,524: INFO: common: json file saved at: scores.json]
[2024-10-29 15:33:34,524: INFO: common: json file saved at: scores.json]
[2024-10-29 15:33:38,571: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-10-29 15:33:39,759: INFO: builder_impl: Assets written to: C:\Users\islam\AppData\Local\Temp\tmpirs6br8q\model\data\model\assets]
[2024-10-29 15:34:17,868: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-10-29 15:35:43,876: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-10-29 15:35:43,888: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 15:35:43,890: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 15:35:43,891: INFO: common: created directory at: artifacts]
[2024-10-29 15:35:43,892: INFO: common: created directory at: artifacts/data_ingestion]
[2024-10-29 15:35:43,892: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-29 15:35:55,775: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-29 15:35:57,681: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-10-29 15:35:57,681: INFO: main: *******************]
[2024-10-29 15:35:57,681: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-10-29 15:35:57,690: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 15:35:57,694: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 15:35:57,695: INFO: common: created directory at: artifacts]
[2024-10-29 15:35:57,695: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-10-29 15:35:58,429: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-10-29 15:35:59,712: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-10-29 15:35:59,713: INFO: main: *******************]
[2024-10-29 15:35:59,714: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-10-29 15:35:59,718: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 15:35:59,721: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 15:35:59,721: INFO: common: created directory at: artifacts]
[2024-10-29 15:35:59,721: INFO: common: created directory at: artifacts\training]
[2024-10-29 15:38:48,573: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-10-29 15:38:48,582: INFO: main: *******************]
[2024-10-29 15:38:48,582: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-10-29 15:38:48,584: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 15:38:48,584: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 15:38:48,592: INFO: common: created directory at: artifacts]
[2024-10-29 15:39:14,032: INFO: common: json file saved at: scores.json]
[2024-10-29 15:39:14,034: INFO: common: json file saved at: scores.json]
[2024-10-29 15:39:18,799: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-10-29 15:39:20,243: INFO: builder_impl: Assets written to: C:\Users\islam\AppData\Local\Temp\tmpotaua234\model\data\model\assets]
[2024-10-29 15:40:01,270: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-10-29 15:42:29,325: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-10-29 15:42:29,325: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 15:42:29,325: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 15:42:29,325: INFO: common: created directory at: artifacts]
[2024-10-29 15:42:29,325: INFO: common: created directory at: artifacts/data_ingestion]
[2024-10-29 15:42:29,325: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-29 15:42:40,227: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-29 15:42:41,872: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-10-29 15:42:41,872: INFO: main: *******************]
[2024-10-29 15:42:41,872: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-10-29 15:42:41,872: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 15:42:41,872: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 15:42:41,872: INFO: common: created directory at: artifacts]
[2024-10-29 15:42:41,888: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-10-29 15:42:42,489: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-10-29 15:42:46,502: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-10-29 15:42:46,502: INFO: main: *******************]
[2024-10-29 15:42:46,518: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-10-29 15:42:46,518: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 15:42:46,518: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 15:42:46,518: INFO: common: created directory at: artifacts]
[2024-10-29 15:42:46,518: INFO: common: created directory at: artifacts\training]
[2024-10-29 15:44:44,749: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-10-29 15:44:44,757: INFO: main: *******************]
[2024-10-29 15:44:44,759: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-10-29 15:44:44,759: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 15:44:44,759: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 15:44:44,759: INFO: common: created directory at: artifacts]
[2024-10-29 15:45:03,591: INFO: common: json file saved at: scores.json]
[2024-10-29 15:45:03,592: INFO: common: json file saved at: scores.json]
[2024-10-29 15:45:07,659: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-10-29 15:45:09,680: INFO: builder_impl: Assets written to: C:\Users\islam\AppData\Local\Temp\tmpkf4dntpz\model\data\model\assets]
[2024-10-29 15:46:00,038: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-10-29 16:39:25,320: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-10-29 16:39:25,320: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 16:39:25,335: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 16:39:25,335: INFO: common: created directory at: artifacts]
[2024-10-29 16:39:25,335: INFO: common: created directory at: artifacts/data_ingestion]
[2024-10-29 16:39:25,335: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-29 16:39:34,992: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-29 16:39:36,966: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-10-29 17:19:21,469: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.100.107:8080]
[2024-10-29 17:19:21,469: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-10-29 17:21:00,694: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:21:00] "GET / HTTP/1.1" 200 -]
[2024-10-29 17:21:04,322: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:21:04] "HEAD / HTTP/1.1" 200 -]
[2024-10-29 17:21:04,572: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:21:04] "GET / HTTP/1.1" 200 -]
[2024-10-29 17:21:51,001: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 49, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users/islam/Downloads/kidney-Disease-classification-Deep-learning-project/src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-10-29 17:21:51,039: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:21:51] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-10-29 17:26:03,480: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-10-29 17:26:03,496: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 17:26:03,501: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 17:26:03,501: INFO: common: created directory at: artifacts]
[2024-10-29 17:26:03,501: INFO: common: created directory at: artifacts/data_ingestion]
[2024-10-29 17:26:03,501: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-29 17:26:13,037: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-10-29 17:26:14,350: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-10-29 17:26:14,350: INFO: main: *******************]
[2024-10-29 17:26:14,350: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-10-29 17:26:14,350: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 17:26:14,350: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 17:26:14,350: INFO: common: created directory at: artifacts]
[2024-10-29 17:26:14,366: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-10-29 17:26:16,150: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-10-29 17:26:16,437: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-10-29 17:26:16,437: INFO: main: *******************]
[2024-10-29 17:26:16,438: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-10-29 17:26:16,442: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 17:26:16,445: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 17:26:16,446: INFO: common: created directory at: artifacts]
[2024-10-29 17:26:16,447: INFO: common: created directory at: artifacts\training]
[2024-10-29 17:29:33,094: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-10-29 17:29:33,094: INFO: main: *******************]
[2024-10-29 17:29:33,094: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-10-29 17:29:33,101: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-29 17:29:33,101: INFO: common: yaml file: params.yaml loaded successfully]
[2024-10-29 17:29:33,101: INFO: common: created directory at: artifacts]
[2024-10-29 17:30:01,449: INFO: common: json file saved at: scores.json]
[2024-10-29 17:30:01,449: INFO: common: json file saved at: scores.json]
[2024-10-29 17:30:17,864: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-10-29 17:30:19,866: INFO: builder_impl: Assets written to: C:\Users\islam\AppData\Local\Temp\tmpbjyu56kn\model\data\model\assets]
[2024-10-29 17:30:46,377: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-10-29 17:34:25,321: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.100.107:8080]
[2024-10-29 17:34:25,329: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-10-29 17:34:43,535: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:34:43] "GET / HTTP/1.1" 200 -]
[2024-10-29 17:34:52,577: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2024-10-29 17:34:53,584: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 49, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users/islam/Downloads/kidney-Disease-classification-Deep-learning-project/src\cnnClassifier\pipeline\prediction.py", line 25, in predict
    if result[0] == 1:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[2024-10-29 17:34:53,591: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:34:53] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-10-29 17:43:18,295: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.100.107:8080]
[2024-10-29 17:43:18,295: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-10-29 17:43:37,109: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:43:37] "GET / HTTP/1.1" 200 -]
[2024-10-29 17:43:43,443: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2024-10-29 17:43:43,959: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 49, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users/islam/Downloads/kidney-Disease-classification-Deep-learning-project/src\cnnClassifier\pipeline\prediction.py", line 25, in predict
    if int(result[0]) == 1:
TypeError: only size-1 arrays can be converted to Python scalars
[2024-10-29 17:43:43,959: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:43:43] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-10-29 17:46:49,819: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.100.107:8080]
[2024-10-29 17:46:49,819: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-10-29 17:46:57,747: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:46:57] "GET / HTTP/1.1" 200 -]
[2024-10-29 17:47:04,889: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2024-10-29 17:47:05,355: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 49, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users/islam/Downloads/kidney-Disease-classification-Deep-learning-project/src\cnnClassifier\pipeline\prediction.py", line 25, in predict
    if result.item() == 1:
ValueError: can only convert an array of size 1 to a Python scalar
[2024-10-29 17:47:05,355: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:47:05] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-10-29 17:48:32,426: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.100.107:8080]
[2024-10-29 17:48:32,426: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-10-29 17:48:34,142: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:48:34] "GET / HTTP/1.1" 200 -]
[2024-10-29 17:48:41,945: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2024-10-29 17:48:42,448: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 49, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users/islam/Downloads/kidney-Disease-classification-Deep-learning-project/src\cnnClassifier\pipeline\prediction.py", line 25, in predict
    if (result[0]) == 1:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[2024-10-29 17:48:42,456: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:48:42] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-10-29 17:51:07,931: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.100.107:8080]
[2024-10-29 17:51:07,931: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-10-29 17:51:14,441: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:51:14] "GET / HTTP/1.1" 200 -]
[2024-10-29 17:51:21,002: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2024-10-29 17:51:21,518: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 49, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users/islam/Downloads/kidney-Disease-classification-Deep-learning-project/src\cnnClassifier\pipeline\prediction.py", line 25, in predict
    if result[0] == 1:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[2024-10-29 17:51:21,534: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:51:21] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-10-29 17:53:22,211: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.100.107:8080]
[2024-10-29 17:53:22,211: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-10-29 17:53:29,059: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:53:29] "GET / HTTP/1.1" 200 -]
[2024-10-29 17:53:36,244: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2024-10-29 17:53:36,677: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 49, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users/islam/Downloads/kidney-Disease-classification-Deep-learning-project/src\cnnClassifier\pipeline\prediction.py", line 25, in predict
    if int(result[0][0]) == 1:
TypeError: only size-1 arrays can be converted to Python scalars
[2024-10-29 17:53:36,694: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:53:36] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-10-29 17:56:10,874: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.100.107:8080]
[2024-10-29 17:56:10,874: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-10-29 17:56:26,085: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:56:26] "GET / HTTP/1.1" 200 -]
[2024-10-29 17:56:32,589: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2024-10-29 17:56:33,069: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 49, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users/islam/Downloads/kidney-Disease-classification-Deep-learning-project/src\cnnClassifier\pipeline\prediction.py", line 25, in predict
    if  result[0, 0] == 1:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[2024-10-29 17:56:33,069: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:56:33] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-10-29 17:58:47,177: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.100.107:8080]
[2024-10-29 17:58:47,177: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-10-29 17:58:54,102: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:58:54] "GET / HTTP/1.1" 200 -]
[2024-10-29 17:59:00,878: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2024-10-29 17:59:00,911: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\islam\.conda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 49, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users/islam/Downloads/kidney-Disease-classification-Deep-learning-project/src\cnnClassifier\pipeline\prediction.py", line 21, in predict
    test_image = np.expand_dims(test_image)
  File "<__array_function__ internals>", line 179, in expand_dims
TypeError: _expand_dims_dispatcher() missing 1 required positional argument: 'axis'
[2024-10-29 17:59:00,911: INFO: _internal: 127.0.0.1 - - [29/Oct/2024 17:59:00] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
